#!/bin/bash -e

: ${ELASTICSEARCH_SERVICE_HOST:?Not defined}

# Add kibana as command if needed
if [[ "${1:0:1}" == '-' ]]; then
    set -- kibana "$@"
fi

# Replace all set environment variables from in the current shell session.
# The environment variables present in the file but are unset will remain untouched.
# Replaced pattern is: ${<ENV_VAR>}
function substenv {
  local in_file="$1"
  local out_file="$2"
  local temp_file=$(mktemp -t substenv.XXXX)
  cat "${in_file}" > ${temp_file}
  compgen -v | while read var ; do
    sed -i "s/\${$var}/$(echo ${!var} | sed -e 's/\\/\\\\/g' -e 's/\//\\\//g' -e 's/&/\\\&/g')/g" "${temp_file}"
  done
  cat "${temp_file}" > "${out_file}" && rm -f "${temp_file}"
}

# Map user to current UID/GID
export USER_ID="$(id -u)"
export GROUP_ID="$(id -g)"
substenv ${HOME}/passwd.in /tmp/passwd
export NSS_WRAPPER_PASSWD=/tmp/passwd
export NSS_WRAPPER_GROUP=/etc/group
export LD_PRELOAD=/usr/lib64/libnss_wrapper.so

sed -ri "s!^(\#\s*)?(elasticsearch\.url:).*!\2 'http://${ELASTICSEARCH_SERVICE_HOST}:9200'!" /opt/kibana/config/kibana.yml

exec "$@"
